baseURL = "https://tiennvcs.github.io"
languageCode = "en-us-vi"
title = "Think like Computer Scientist"
paginate = 5
googleAnalytics = ""
disqusShortname = "hugo-minima"
theme = "minima"

# Author has some of your information to be shown on the home 
# page of your blog.
[author]
name = "Tien Nguyen"
slogon = "THINKING BEFORE DOING, RETHINKING AFTER RESOLVING"
description = "This blog aim to sharing my knowledge about Programming, Math, Machine learning under point of view of Computer Science student."
short_bio = "Currently, I am a research engineer at AI research engineer at Viettel High Technology Industries Corporation (VHT). I hold a Bachelor's degree in computer science from Vietnam National University Ho Chi Minh City - Univeristy of Information Technology."

[params]
# iam is the beginning words of your self-introduction.
iam = "Hi, I'm"
# The subtitle will be shown after the title of your blog site
#  in a format like "title - subtitle".
subtitle = ""
# Comment decides the comment plugin used on your blog site, 
# available plugins: disqus, ovo.
comment = "disqus"
# timeformat 
timeformat = "Jan 2, 2006"
# switch for turning on/off lights.
switch = ["ğŸŒš", "ğŸŒ"]


# OvO is a comment plugin written by the author of Minima. 
# It is enabled when params.comment is set "ovo". You can
# find its documentation on https://github.com/ovojs/ovo.
# If you are using disqus, just ignore this field.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you select to use must have both the width and the
# height set 18. If you don't wanna put the svg code in this config
# file, you can instead save them to the `data/svg.toml` file under 
# the root directory of your blog using a format like `name = '<svg>'`
[[params.social]]
name = "github"  
url = "https://github.com/tiennvcs"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tiennvcs"
svg = ""


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "ğŸ Home"
url = "/"
weight = 1
[[menu.main]]
name = "ğŸ…Publications"
url = "/public"
weight = 2
[[menu.main]]
name = "ğŸ…Projects"
url = "/project"
weight = 3
[[menu.main]]
name = "ğŸ´Math"
url = "/math"
weight = 4
[[menu.main]]
name = "ğŸ„ML"
url = "/ml"
weight = 5
[[menu.main]]
name = "ğŸ‡Mixed"
url = "/mixed"
weight = 6
[[menu.main]]
name = "ğŸ‡Collection"
url = "/collection"
weight = 7
[[menu.main]]
name = "ğŸ‰About me"
url = "/about"
weight = 8


[taxonomies]
# category = ["DSA", "MA4ML", "Machine learning", "Computer vision"]
# tag = ["Data structure and algorithm", "Math for Machine learning", "Machine learning", "Computer Vision"]
# series = "series"
category = "categories"
tag = "tags"
series = "series"

[markup.highlight]
lineNos = true
noClasses = false

enableGitInfo =true
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]